package parser

type ErrorCode int

const (
	ERROR_NONE ErrorCode = iota
	ERROR_SYNTAX
	ERROR_UNSUPPORTEDSQL
)

type ConflictClause int

const (
	CONFLICT_NONE ConflictClause = iota
	CONFLICT_ROOLBACK
	CONFLICT_ABORT
	CONFLICT_FAIL
	CONFLICT_IGNORE
	CONFLICT_REPLACE
)

type OrderClause int

const (
	ORDER_NONE OrderClause = iota
	ORDER_ASC
	ORDER_DESC
)

type FkAction int

const (
	FKACTION_NONE FkAction = iota
	FKACTION_SETNULL
	FKACTION_SETDEFAULT
	FKACTION_CASCADE
	FKACTION_RESTRICT
	FKACTION_NOACTION
)

type FkDefType int

const (
	DEFTYPE_NONE FkDefType = iota
	DEFTYPE_DEFERRABLE
	DEFTYPE_DEFERRABLE_INITIALLY_DEFERRED
	DEFTYPE_DEFERRABLE_INITIALLY_IMMEDIATE
	DEFTYPE_NOTDEFERRABLE
	DEFTYPE_NOTDEFERRABLE_INITIALLY_DEFERRED
	DEFTYPE_NOTDEFERRABLE_INITIALLY_IMMEDIATE
)

type ConstraintType int

const (
	TABLECONSTRAINT_PRIMARYKEY ConstraintType = iota
	TABLECONSTRAINT_UNIQUE
	TABLECONSTRAINT_CHECK
	TABLECONSTRAINT_FOREIGNKEY
)
